language: c
compiler:
- clang
- gcc
before_script:
- mkdir build && pushd build && cmake .. && make && make test && popd
- rm -rf build
script:
- mkdir dist && pushd dist && cmake .. && popd
- mv dist hcephes-`cat VERSION`
- tar czf hcephes-`cat VERSION`.tar.gz hcephes-`cat VERSION`
- rm -rf dist
after_failure:
- rm -rf * && cmake .. && make && make test ARGS="-V"
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: releases
  on:
    repo: limix/hcephes
    branch: master
