language: c
sudo: false
compiler:
- clang
- gcc
script:
- mkdir build && pushd build
- cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=Release
- make && make test && make install
- popd && rm -rf build
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/include/hcephes.h;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libhcephes.so;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libhcephes_static.a;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/include/hcephes.h;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libhcephes.dylib;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -e $TRAVIS_BUILD_DIR/lib/libhcephes_static.a;
  fi
after_success:
- mkdir dist && pushd dist && cmake .. -DCMAKE_BUILD_TYPE=Release && popd
- mv dist hcephes-`cat VERSION`
- tar czf hcephes-`cat VERSION`.tar.gz hcephes-`cat VERSION`
- rm -rf dist
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: dT6Pv7ZGiQQ1vBnj2EAGUZo9iwXY5cWahCVkyjRhT8TI3YNg4lzY7emFEdMOOFh7pDwN17s0tsYM3ic7ah/QSmX68vo5HZ3oxN45J5TKeMx4q2VcU3IJLXnyr3XvQIF0IOCLBwQvB3xWr2CnirWZeFzMq2GexyKoXiGTOAMXnbXu0vQFV3+SHei6jMXowcyclwsx4eBrk3cQ4KAQhehlqFW2bpjoi0xEue8LBCEXrrn/Lo7QRxIsxzOnfxZmwUyd7bcpeBwyu0rgwZYcq+tpYxzHH8ReFkRg7ah64TY/NRRF2TuEYrZ2/OC9AXGx7PqvBRSZAwG0tRtO+PtDSAFeEFhmS7vOE2/EXCeH1889c+wPFL+X9lFa9m/T8m53XZCQERC2ERdo1BojyFKqatDN2YqNkThlUf+CjrvmOHFOnzyMiCucjtFhsj30UoWkXuUptMogwkfYve6W0Xzg/1bMp8Ye0kufNWVfcQKZk8477mwoVubXPguLs18yG/U/LBjwo7njOBBMJT3W05M6v6bb2vPjGvtZF9j0KRTrNmto0aJGZMScQBPTI46cR6i9mA7S9nlbhL/nisJKgDsd0Tfd2w9pYDD1bl8hrvNL4dDbx+ryzQCZH4bf5lHovtbjUHA4RM2em8zJ8tlix9TQ4m/c/v9ruX8jm7irVGgO/DJgsFM=
  on:
    tags: true
    repo: limix/hcephes
    branch: master
